"""TrustWipe Windows Native CLI Module."""

from .trustwipe_eraser import (
    FSCTL_DISMOUNT_VOLUME,
    FSCTL_LOCK_VOLUME,
    GENERIC_READ,
    GENERIC_WRITE,
    GET_LENGTH_INFORMATION,
    WIN32_FIND_STREAM_DATA,
    WinDriveWipeResult,
    WinFileEraseResult,
    check_windows_wipe_safety,
    detect_windows_filesystem,
    dismount_and_lock_windows_volume,
    enumerate_ntfs_streams_win32,
    erase_batch_windows,
    erase_folder_windows,
    erase_single_file_windows,
    get_windows_target_size,
    scrub_alternate_data_streams,
    win32_clear_attributes,
    win32_flush_buffers,
    wipe_drive_or_partition_windows,
)

__all__ = [
    "FSCTL_DISMOUNT_VOLUME",
    "FSCTL_LOCK_VOLUME",
    "GENERIC_READ",
    "GENERIC_WRITE",
    "GET_LENGTH_INFORMATION",
    "WIN32_FIND_STREAM_DATA",
    "WinDriveWipeResult",
    "WinFileEraseResult",
    "check_windows_wipe_safety",
    "detect_windows_filesystem",
    "dismount_and_lock_windows_volume",
    "enumerate_ntfs_streams_win32",
    "erase_batch_windows",
    "erase_folder_windows",
    "erase_single_file_windows",
    "get_windows_target_size",
    "scrub_alternate_data_streams",
    "win32_clear_attributes",
    "win32_flush_buffers",
    "wipe_drive_or_partition_windows",
]
