#!/usr/bin/env python3
"""Regenerate the skill's carving reference from the live signature table.

The reference used to carry a hand-written table of "10 magic-byte signatures".
The live table had 62 signatures across 51 extensions at the time this was
written, so the guidance an agent reads was describing a tool that no longer
existed. A duplicated table drifts; a generated one cannot.

Run this after changing `SIGNATURES` or the boundary rules, and commit the
result. `tests/cli/test_skill_reference_sync.py` fails if the checked-in file and
this generator disagree, which is what stops the drift from coming back.

    python tools/gen_carving_reference.py
    python tools/gen_carving_reference.py --check     # exit 1 if out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from s0.carve import boundary  # noqa: E402
from s0.carve.signatures import SIGNATURES  # noqa: E402

TARGET = REPO / "skills" / "s0-forensics" / "references" / "carving-signatures.md"

#: Extra columns the generated table cannot know: the note that an extension is
#: recovered through a sibling container, or that it is refused.
NOTES = {
    "docx": "ZIP container; sized by the end-of-central-directory",
    "xlsx": "ZIP container; sized by the end-of-central-directory",
    "pptx": "ZIP container; sized by the end-of-central-directory",
    "doc": "OLE2/CFB; sized by walking the directory chain",
    "mdb": "OLE2/CFB; sized by walking the directory chain",
    "mkv": "EBML; declared-size, unknown-size and unknown-size-cluster Segment",
    "webm": "EBML; declared-size, unknown-size and unknown-size-cluster Segment",
    "mka": "EBML; declared-size, unknown-size and unknown-size-cluster Segment",
    "mp4": "ISO-BMFF; sample table for progressive, `moof` keys for fragmented",
    "mov": "ISO-BMFF; sample table for progressive, `moof` keys for fragmented",
    "m4v": "ISO-BMFF; sample table for progressive",
    "avi": "RIFF; length from `idx1` or OpenDML `indx`",
    "bz2": "decompressor-reported end, exact",
    "xz": "decompressor-reported end, exact",
    "lz4": "frame and block header walk, no decoder needed",
    "zst": "frame and block header walk, no decoder needed",
    "tiff": "IFD chain plus strip extents; compressed TIFF is refused",
    "jp2": "box walk to EOC",
    "aiff": "`FORM` declared size",
    "mid": "`MTrk` chunk walk",
    "rtf": "group nesting must close",
    "class": "constant pool and member tables",
    "rar": "RAR5 block chain to end-of-archive",
    "dat": "`hbin` chain; a hive with no terminator is reported truncated",
    "lnk": "`LinkSize`",
    "pf": "prefetch v3 original-file size; earlier versions refused",
}

#: Refusals worth stating in the guidance, because an agent will otherwise try
#: to work around them.
REFUSED = (
    "Compressed TIFF (LZW, Deflate, PackBits) is **refused**: a compressed "
    "strip's length is not its byte count, so the strip geometry produces a "
    "confident wrong answer.\n"
    "  Windows INI and Berkeley DB are **refused**: text with no length and no "
    "terminator.\n"
    "  A Matroska cluster whose header was overwritten is **not reconstructed**: "
    "with no in-band key left, any position is a guess, and a guessed position "
    "yields a file that plays the wrong footage rather than no footage.\n"
    "  ext4 **journal (jbd2) filenames are not recovered**. The journal reader "
    "works and is verified against a real superblock, but proving end-to-end name "
    "recovery needs a mounted filesystem. Deleted ext4 files are reported as "
    "`inode<N>` with their data recovered -- which is honest, and not a name."
)


def _humanise(magic: bytes) -> str:
    printable = "".join(chr(b) if 32 <= b < 127 and chr(b) not in "|\\`" else "." for b in magic)
    printable = printable.replace("*", r"\*")
    hexed = " ".join(f"{b:02X}" for b in magic)
    return f"`{hexed}` (`{printable}`)" if printable.strip(".") else f"`{hexed}`"


def _size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return f"{n // 1 if unit == 'B' else n}" + f" {unit}"
        n //= 1024
    return f"{n} GB"


def render() -> str:
    exts = {}
    for sig in SIGNATURES:
        exts.setdefault(sig.extension.lower(), sig)
    resolvable = sorted(e for e in exts if boundary.has_boundary_rule(e))
    unresolved = sorted(e for e in exts if not boundary.has_boundary_rule(e))

    out = [
        "# Carving Signatures, File Formats & Structural Gates",
        "",
        "<!-- GENERATED by tools/gen_carving_reference.py. Do not hand-edit. -->",
        "<!-- Regenerate with: python tools/gen_carving_reference.py -->",
        "",
        "This reference is derived from the live signature table, so it cannot",
        "describe a tool that no longer exists. If a format is not listed here, it",
        "is not a signature s0 has.",
        "",
        "---",
        "",
        "## 1. At a glance",
        "",
        f"- **{len(SIGNATURES)} signatures** across **{len(exts)} extensions**.",
        f"- **{len(resolvable)} extensions** have a structural boundary rule, so "
        "the exact end is derived from the format.",
        f"- **{len(unresolved)} extensions** have no such rule: they are sized "
        "from a declared field or footer where the format has one, and are "
        "otherwise carved to the signature's `max_size`.",
        "",
        "A boundary rule is what separates a derived length from a guessed one. "
        "Where one exists, the end comes from the structure; where one does not, "
        "the report says so rather than implying precision.",
        "",
        "---",
        "",
        "## 2. Format matrix",
        "",
        "| Ext | Category | Magic | Sizing | Notes |",
        "|---|---|---|---|---|",
    ]
    for ext in sorted(exts):
        sig = exts[ext]
        rule = ("structural" if boundary.has_boundary_rule(ext)
                else "declared field / footer")
        magic = _humanise(sig.header[:12])
        note = NOTES.get(ext, "")
        out.append(f"| `{ext}` | {sig.category} | {magic} | {rule} | {note} |")

    out += [
        "",
        "### Extensions without a structural boundary rule",
        "",
    ]
    for ext in unresolved:
        sig = exts[ext]
        out.append(f"- `{ext}` — {sig.name}. Sizing: declared field or footer; "
                   f"carve ceiling {_size(sig.max_size)}.")
    out += [
        "",
        "If you need an exact length for one of these, the honest options are a "
        "new boundary rule for the format or accepting the caveat in the report. "
        "Guessing an end for a container produces a file that looks complete and "
        "is not.",
        "",
        "---",
        "",
        "## 3. Refusals",
        "",
        REFUSED,
        "",
        "A refusal names its reason in `recovery_index.json` and the CLI output. "
        "Report it; do not route around it.",
        "",
        "---",
        "",
        "## 4. Fragment reassembly",
        "",
        "Fragments are ordered by the logical key **inside** each fragment, not "
        "by position on the volume:",
        "",
        "| Container | Ordering key | Also recorded |",
        "|---|---|---|",
        "| ISO-BMFF | `mfhd.sequence_number` (dense, from 1) | `tfdt.baseMediaDecodeTime` |",
        "| Matroska | `Cluster.Timestamp` | block count and sizes |",
        "",
        "Measured: byte-exact recovery of an 8-fragment MP4 and a 4-cluster "
        "Matroska under every permutation tested, including exact reverse order, "
        "with unrelated evidence between each pair.",
        "",
        "Three checks stand between a candidate and a file: **contiguity** for "
        "dense sequence keys (a hole is named and the assembly refused, because "
        "bridging a hole yields a file that decodes to a shorter video with no "
        "visible error); **projection**, where `tfdt[i] + sum(sample durations)` "
        "must equal `tfdt[i+1]`, an exact identity; and a **reparse** through the "
        "format's own parser.",
        "",
        "Timecode keys are deliberately not held to contiguity: a recorder that "
        "drops frames leaves a timecode jump, and that is not a lost fragment.",
        "",
        "---",
        "",
        "## 5. Filesystem-aware structure engines",
        "",
        "Before falling back to sliding-window signature carving, `s0 carve` "
        "probes for filesystem metadata:",
        "",
        "- **NTFS ($MFT)** — reads MFT records, `$FILE_NAME` and `$DATA` "
        "attributes, and reassembles non-resident run-lists. `$FILE_NAME` holds a "
        "full volume-relative path, which is why NTFS is the one filesystem where "
        "an original *path* is recovered rather than just a name.",
        "- **ext4 (inodes)** — block group descriptors, inode bitmaps, extent "
        "trees. Names come from directory entries, which record no parent.",
        "- **FAT32 / exFAT** — directory sectors for deleted markers (`0xE5` in "
        "FAT32). FAT32 long names carry a checksum of the 8.3 entry they belong "
        "to; a name recovered from a *deleted* 8.3 entry cannot be verified, and "
        "exFAT has no checksum at all. `name_provenance` says which case applies.",
        "- **Registry (`dat`)** — the `hbin` chain. A hive with no terminating "
        "empty block is reported truncated rather than sized.",
        "",
        "---",
        "",
        "## 6. Boundary methods in the report",
        "",
        "Each recovered file records `boundary_method`. The values mean:",
        "",
        "| Method | Meaning |",
        "|---|---|",
        "| `declared_size` | The format states its own length. |",
        "| `container_walk` | The end was derived by walking the structure. |",
        "| `footer_anchored` | A trusted closing marker was found. |",
        "| `frame_sequence` | A validated run of frames bounds the data. |",
        "| `decompress_to_end` | The decoder reported how much it consumed. |",
        "| `continuous_sync_run` | A packet sync run, with no declared end. |",
        "| `undetermined` | No defensible end was available. |",
        "| `max_size_fallback` | Carved to the ceiling; **weakest**, and reported as such. |",
        "",
        "A `max_size_fallback` on a container format means the tool could not size "
        "it and stopped at the ceiling. Say so when you report it.",
        "",
    ]
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the checked-in file is out of date")
    args = ap.parse_args()
    text = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        if current != text:
            print(f"out of date: {TARGET}", file=sys.stderr)
            print("run: python tools/gen_carving_reference.py", file=sys.stderr)
            return 1
        print(f"in sync: {TARGET}")
        return 0
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
